HOST	      = DESKTOP-FK

DEST	      = ./                    

EXTHDRS	      =

HDRS	      =

FC	      = gfortran

FFLAGS	      = -g

LDFLAGS	      = -g

LIBS	      =

LINKER	      = gfortran

MAKEFILE      = Makefile

OBJS	      = VPA-main.o \
		VPA-Lib.o \
		RICBES.o \
		Potential.o \
		DLSODALIB.o \
		WKB.o

PRINT	      =    

PRINTER	      =      

PROGRAM	      = vpa

SRCS	      = VPA-main.f90 \
		VPA-Lib.f \
		RICBES.f \
		Potential.f \
		DSLODALIB.f \
		WKB.f

PORTABLE      = VPA.FORT

all:		$(PROGRAM)

$(PROGRAM):     $(OBJS) $(LIBS)
		@echo -n "Loading $(PROGRAM) ... "
		@$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM).$(HOST)
		@echo "done"

clean:;		@rm -f $(OBJS)

depend:;	@mkmf -f $(MAKEFILE) PROGRAM=$(PROGRAM) DEST=$(DEST)

index:;		@ctags -wx $(HDRS) $(SRCS)

install:	$(PROGRAM)
		@echo Installing $(PROGRAM) in $(DEST)
		@cp $(PROGRAM).$(HOST) $(DEST)/$(PROGRAM)

print:;		@$(PRINT) $(HDRS) $(SRCS)

list:		$(SRCS)
		@$(PRINT) $?
		@echo '' >> list
		@echo Listed files are: >> list
		@echo $? >> list
		@echo `date` >> list

program:        $(PROGRAM)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)

combine:;       @cat $(SRCS)|tr a-z A-Z > $(PORTABLE)

$(DEST)/$(PROGRAM): $(SRCS) $(LIBS) $(HDRS) $(EXTHDRS)
		@make -f $(MAKEFILE) DEST=$(DEST) install

RCS:		
		@mkdir ./RCS

ci:;		@make RCS
		@ci $(SRCS)

co:;		@co -q -l $(SRCS)

register:;	@make RCS
		@ci $(SRCS)
		@co -q -l $(SRCS)

$(SRCS):;	@co $(SR:)
